language: python
python:
- '3.7'
dist: xenial
install:
- pip install numpy cython
- pip install click
- pip install -i https://test.pypi.org/simple/ algorithm-tester
- python setup.py install
- python -m pip install .[dev]
script:
# - make -C docs doctest
- python setup.py test